### ISSUE TITLE
Show an URL after deploying a WAR-like artefact

### ISSUE THREAD

**Issue by hpehl** [hal/hal.next#114]
After the user has deployed something which has a context-root

```
/deployment=foo.war/subsystem=undertow:read-attribute(name=context-root)
```

show an URL to let the user check whether the deployment was successful. 

Depends on #109 and relates to https://issues.jboss.org/browse/WFLY-5321

**Comment by claudio4j** [comment]
Resolved as https://github.com/hal/hal.next/commit/5b81a5468f5529f31b03ee91c9df33bdd6619f7b
