### ISSUE TITLE
Random "IllegalStateException: Another dialog is still open" when switching store on distributed-cache

### ISSUE THREAD

**Issue by claudio4j** [hal/hal.next#146]
There is a random problem when switching store on a distributed-cache of infinispan subsystem. The moment the user clicks on the drop down there is an error:
```
IllegalStateException: Another dialog is still open. Only one dialog can be open at a time. Please close the other dialog!
```
Then the first dialog is open, but unusable.
The analysis on `StoreElement.attach()` method indicates the event call on `SelectBoxBridge.Single.element(selectStore).onChange((event, index) ` is called two times. But this is random behavior.

**Comment by hpehl** [comment]
Can no longer reproduce
