### ISSUE TITLE
Datasources in Management Model not handled correctly

### ISSUE THREAD

**Issue by michpetrov** [hal/hal.next#149]
As per [WFLY-9439](https://issues.jboss.org/browse/WFLY-9439) datasources are supposed to be singletons but since there can be an unlimited number of them the model browser is not handling that correctly - e.g. trying to add a new datasource doesn't let you choose a name (supplying `no_singleton` in the background). On the other hand the required attributes are not enough to add a new datasource anyway.

**Comment by hpehl** [comment]
I'm afraid there's no easy solution for this. Since datasources are kind of special singletons, the generic model browser cannot handle them like other "regular" singletons. 

That's why I'm closing this issue as `wontfix`.
