### ISSUE TITLE
Repeatedly clicking on row in a table enables and disables editing of the item

### ISSUE THREAD

**Issue by zebrik** [hal/hal.next#159]
See [screencast](https://drive.google.com/file/d/1lnbURBwucKuFJ6EuWFjHm2hKPbGIe-IG/view).
Is this intentional? This behavior is breaking your tests like [DeploymentScannerTest](https://github.com/hal/testsuite.next/blob/master/tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/deploymentscanner/DeploymentScannerTest.java) if the same item is used in more tests and thus clicked more times without page refresh.

**Comment by hpehl** [comment]
Yes this is intentional. The first click selects the item, the second deselects the item and clears the form (same behaviour as pressing space on a selected item in the current console).

That's why we use different resources in our tests.

**Comment by zebrik** [comment]
OK, I will clean up tests accordingly since in some not isolated tests resources are reused resulting in false alarms.
