### ISSUE TITLE
Incorrect editing of messaging bridge

### ISSUE THREAD

**Issue by zebrik** [hal/hal.next#160]
Reproducer:

1. add messaging bridge without the password but with credential reference specified, e.g.
`/subsystem=messaging-activemq/server=default/bridge=experiment:add(credential-reference={clear-text=pass}, queue-name=test-queue, discovery-group=test-group)`
`reload`
2. try to edit some attribute of the bridge using HAL.Next console, e.g. Check Period
It's impossible untill you manually erase default value from password field to undefine already undefined value. Then it's possible to save but console performes 3 actions:
- writes edited attribute, e.g. check-period (correctly)
- undefines already undefined value of password attribute (uselessly)
- undefines credential-reference attribute (wrongly!)

**Comment by hpehl** [comment]
There's a bug in the class where we calculate the operations necessary after a form was modified. I've already fixed that, but it needs more testing. This removes the third operation from above. 

The second operation won't go away though. In this case it's useless, but it's necessary in other situations. And I don't want to add another exception for that case (the code is complex enough).
