### ISSUE TITLE
Max-history parameter is not passed when enabling configuration changes via HAL

### ISSUE THREAD

**Issue by zebrik** [hal/hal.next#161]
no matter what is the configured max number

**Comment by zebrik** [comment]
I have changed the subject of this issue since I have found that all changes are shown just the max-history parameter wasn't passed.

**Comment by hpehl** [comment]
Thanks. Yes it's a bug and it seems there's an easy fix. Also a good opportunity to write a test case together with the actual bug fix.

**Comment by hpehl** [comment]
### Standalone
```
/subsystem=core-management/service=configuration-changes
```

### Domain
Servers are configured using their profile:
```
/profile=<name>/subsystem=core-management/service=configuration-changes
```

Hosts are configured using:
```
/host=foo/server=bar/subsystem=core-management/service=configuration-changes
```
