### ISSUE TITLE
Implement missing runtime subsystems

### ISSUE THREAD

**Issue by hpehl** [hal/hal.next#37]
Implement these subsystems to be en par with the current console:
- [x] Batch
- [x] EJB (MDB, Singleton, Stateful & Stateless SB)
- [x] IO (servers sub-resource)
- [x] Messaging
- [x] Transactions
- [x] Transaction Logs
- [x] Web / HTTP
- [x] Web Services

Implement these new subsystems:
- [x] JAX-RS (using the new `show-resources` operation (see [WFLY-7024](https://issues.jboss.org/browse/WFLY-7024) and [WFLY-7210](https://issues.jboss.org/browse/WFLY-7210))

**Comment by claudio4j** [comment]
I will work on webservices screen.
