### ISSUE TITLE
Fix metadata resolution using recursive=true|false

### ISSUE THREAD

**Issue by hpehl** [hal/hal.next#50]
If two metadata relevant classes (e.g. a finder column and a presenter) are annotated with the same `@Requires` annotation and one of the classes uses `recursive=true` and the other `recursive=false` (default), the resolution works not correctly. 

If it happens that the `recursive=false` class is processed first, the second with `recursive=true` is not processed and thus the recursive metadata never gets processed. The metadata registry takes only the address into account, but not whether the resolution should happen recursively or not.

When fixed, adjust the `@Requires` annotations on these columns and presenters:

- `org.jboss.hal.client.configuration.subsystem.security.SecurityDomainColumn`
- `org.jboss.hal.client.configuration.subsystem.security.SecurityDomainPresenter`
- `org.jboss.hal.client.configuration.subsystem.infinispan.CacheContainerColumn`
- `org.jboss.hal.client.configuration.subsystem.infinispan.CacheContainerPresenter`

**Comment by hpehl** [comment]
After some analysis there's no real solution atm. The only thing you can do is to not use the same address with different recursive flags on different classes.

**Comment by claudio4j** [comment]
The mentioned Column and Presenter already contains the @Requires annotation.

**Comment by hpehl** [comment]
There's another real issue related to this: 

If you select a resource (say subsystem=remoting) in the model browser, the model browser **always** processes the resource using `recursive=false`. If you then try to open the remoting presenter, an metadata error is thrown because the presenter requires `recursive=true`.
