### ISSUE TITLE
Internal error when trying to add a Datasource

### ISSUE THREAD

**Issue by mayerw** [hal/hal.next#63]
When I push the 'Add Datasource' or 'Add XA Datasource' an internal error is fired with details 'newValue is null'

**Comment by hpehl** [comment]
Can you give more details, please. What versions do you use (WildFly and HAL.next)? What operation mode are you running (domain or standalone)? 

You should get these informations from the about dialog when you click on the version number in the footer.

**Comment by hpehl** [comment]
I guess you're running standalone mode. If so this should be fixed with 024975ef40fdd3c4448289d7d531621a6e0dbceb, otherwise please reopen.

**Comment by mayerw** [comment]
Hi Harald,

This is my environment:

Regards
Wolfgang

Am Montag, 16. Januar 2017, 04:38:34 CET schrieb Harald Pehl:
> Can you give more details, please. What versions do you use (WildFly and
> HAL.next)? What operation mode are you running (domain or standalone)?
> 
> You should get these informations from the about dialog when you click on
> the version number in the footer.
