### ISSUE TITLE
Update configuration screens to include Elytron resources and attributes

### ISSUE THREAD

**Issue by hpehl** [hal/hal.next#69]
Elytron updates several subsystems such as: iiop-openjdk, messaging-activemq, datasource, resource-adapter, host/domain-controller or undertow.

Update the following subsystems to include new attributes and resources and take care of the alternatives behaviour:

- [x] datasource/data-source
- [x] datasource/xa-data-source
- [x] mail/server
- [x] messaging-activemq/jms-bridge
- [x] messaging-activemq/server
- [x] messaging-activemq/server/bridge
- [x] messaging-activemq/server/pooled-connection-factory
- [x] resource-adapters/resource-adapter
- [x] resource-adapters/resource-adapter/connection-definitions
- [x] undertow/application-security-domain

Resources skipped at the moment:
- /host=*/core-service=management/access=audit/syslog-handler=*/protocol=*

**Comment by claudio4j** [comment]
I will work on undertow/application-security-domain

**Comment by hpehl** [comment]
Thanks. I've started to implement building blocks for credential references [1]. My plan is to come up with some reusable code which we can use to add support for `credential-reference` across subsystems. I used [2] as a first use case.

[1] https://github.com/hal/hal.next/blob/develop/core/src/main/java/org/jboss/hal/core/subsystem/elytron/CredentialReference.java
[2] https://github.com/hal/hal.next/blob/develop/app/src/main/java/org/jboss/hal/client/configuration/subsystem/mail/MailSessionView.java

**Comment by claudio4j** [comment]
I removed modcluster from the list, as there is no credential-reference in it.
