### ISSUE TITLE
Show boot errors on runtime page and on reload messages

### ISSUE THREAD

**Issue by ggam** [hal/hal.next#70]
Currently HAL indicates that the server is correctly running or reloaded succesfully even when boot errors occurred. As it works at the moment, one has to check the server logs to verify it actually has started correctly.

WildFly provides an operation to list boot errors under `/core-service=management:read-boot-errors()`.

I propose to show that information on start/restart/reload messages and make it available on the runtime tab.

**Comment by hpehl** [comment]
I was not aware of this operation, but it totally makes sense to use it for runtime.
