### ISSUE TITLE
Show context root for WAR deployments

### ISSUE THREAD

**Issue by ggam** [hal/hal.next#71]
When a WAR is deployed, its runtime name is taken as the context root only if no `jboss-web.xml` is provided. To actually view the effective context path for a deployment, one has to navigate through the management model of the deployment, to the Undertow Subsystem.

That's unintuitive for new users. My proposal is to show the context root right on the deployment details view (when you select a deployment).

EAR deployments containing multiple WARs may need to list all its context roots.

**Comment by hpehl** [comment]
Good point. Makes sense to me.
