### ISSUE TITLE
Required resources missing due to duplicate ids

### ISSUE THREAD

**Issue by michpetrov** [hal/hal.next#75]
There are several annotations using duplicate strings making the resource registry incomplete.

One instance where this currently causes issues is in Configuration > Subsystems > Datasources & Drivers > Datasources: new Datasource cannot be added due to missing metadata. This is caused by a duplicate id between [DataSourcePresenter](https://github.com/hal/hal.next/blob/develop/app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourcePresenter.java#L62-L63) and [DataSourceColumn](https://github.com/hal/hal.next/blob/master/app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceColumn.java#L80-L81).

I've changed the RequiredResourceProcessor to report conflicts, this is the result:

> [ERROR] diagnostic: error: could not add resources for log-file
[ERROR] diagnostic: error: could not add resources for jpa-runtime
[ERROR] diagnostic: error: could not add resources for data-source-runtime
[ERROR] diagnostic: error: could not add resources for interface
[ERROR] diagnostic: error: could not add resources for logging-profile
[ERROR] diagnostic: error: could not add resources for resource-adapter
[ERROR] diagnostic: error: could not add resources for undertow-server
[ERROR] diagnostic: error: could not add resources for undertow-servlet-container
[ERROR] diagnostic: error: could not add resources for security-domain
[ERROR] diagnostic: error: could not add resources for data-source-configuration
[ERROR] diagnostic: error: could not add resources for messaging-server
[ERROR] diagnostic: error: could not add resources for jms-bridge
[ERROR] diagnostic: error: could not add resources for mail-session
[ERROR] diagnostic: error: could not add resources for server-group-deployment
[ERROR] diagnostic: error: could not add resources for deployment

I haven't checked those, it's possible they require the same resources and so there are no issues, though at the very least I assume there shouldn't be duplicates between NameTokens and Ids.

**Comment by hpehl** [comment]
Good point. I'll check the IDs used for applications / places and columns. I think a dedicated interface with IDs used for columns makes sense. 

However I could not reproduce the error with the missing metadata!?

**Comment by michpetrov** [comment]
Strange, I don't get the error if I run the published standalone jar. However I get it if I run devmode or try to build the jar myself. I'm guessing the resources are being ordered differently on my system. [This](https://gist.github.com/michpetrov/bc508428c914271b7b8d8a6dbe0fda24) is what the generated registry looks like.

**Comment by hpehl** [comment]
Hmm I don't see the error neither in devmode nor with standalone jar

**Comment by hpehl** [comment]
Duplicate IDs with different set of required resources are now detected by the related annotation processor and are a build time error.
