### ISSUE TITLE
DMR errors when switching stores for Infinispan cache containers

### ISSUE THREAD

**Issue by hpehl** [hal/hal.next#82]
Switching stores in a distributed cache causes DRM errors in the generated composite operation. Might be related to the fact that the `store=string-jdbc` singleton was renamed to `store=jdbc`.

**Comment by claudio4j** [comment]
This problem is random, it happened to me only two times in a series of testing, the composite operation is as:
```
batch
/profile=full-ha/subsystem=infinispan/cache-container=ejb/distributed-cache=dist/store=file:remove
/profile=full-ha/subsystem=infinispan/cache-container=ejb/distributed-cache=dist/store=jdbc:add(data-source=ExampleDS)
run-batch
```
But it always works on CLI. I will let it as is.

**Comment by hpehl** [comment]
Can no longer reproduce
