### ISSUE TITLE
Enable upload of files to existing deployments, now you can just download bits

### ISSUE THREAD

**Issue by rsvoboda** [hal/hal.next#93]
This is followup of https://github.com/hal/hal.next/issues/92 - Enabled OFF case

I went to view the deployment structure and navigated to WEB-INF.
I wanted to upload missing hibernate5-quickstart-ds.xml I removed before.
My goal was to "patch it" and successfully enable the deployment.

I think with latest changes in management it should be possible to upload data to deployments (I guess in exploded mode only ?)

Please enable upload of files to existing deployments as part of hal.next development. This could be pretty handy feature.

**Comment by hpehl** [comment]
Enable for exploded deployments. Use the operation `/deployment=<exploded-deployment>:add-content()` to upload content to the deployment.
