### ISSUE TITLE
Enable direct editing of files in deployment - e.g. web.xml, html, css files

### ISSUE THREAD

**Issue by rsvoboda** [hal/hal.next#94]
Enable direct editing of files in deployments, similar to direct edit feature available in GitHub.

This could be handy when you need to reconfigure something in web.xml etc.
Basically anything from https://docs.jboss.org/author/display/WFLY/Deployment+Descriptors+used+In+WildFly and *.html/*.css/*.js

**Comment by hpehl** [comment]
Great idea. Requires an exploded deployment. See #93 for details about the DMR operation.
