### ISSUE TITLE
Unable to upload files to Deployments Section with Safari

### ISSUE THREAD

**Issue by PeterFalken** [hal/hal.next#97]
I'm running the lasses version of Safari (10.1 - build 12603.1.30.0.34) on macOS Sierra 10.12.4 and When I select the WAR file to upload and hit next - it never finishes the upload. The functionality works correctly with Firefox 53.

I've noticed the same behavior with version 2.8.x of HAL on Wildly 10.x as well.
Could this be an issue with how Safari is handling the uploads??

Regards,
Peter

**Comment by hpehl** [comment]
Which way do you use to start HAL.next (NPM, standalone, docker, devmode)? Also could you give the exact version (from the about dialog).

**Comment by hpehl** [comment]
After some more tests, there's also a minor issue in FF: 

1. Add a deployment using the wizard
1. Select the file using drag and drop on the wizard
1. The file seems to be recognised since the filename is displayed 
1. Click 'Next'
1. An error occurs saying "No content specified. Please select a file to upload."

**Comment by hpehl** [comment]
I'd like to postpone this issue until #40 has been resolved.

**Comment by PeterFalken** [comment]
Harald,
I was using the standalone JAR to access the Management Console.
Attached is the screen grab of the Safari About dialog.

I did notice that the drag and drop feature didn't work on Safari nor Firefox, but since the work around was to select the file, I didn't mentioned it.

![safariversion](https://cloud.githubusercontent.com/assets/2557898/25959098/e66d132c-362f-11e7-962a-37fe56faec9c.jpeg)

**Comment by hpehl** [comment]
Can no longer reproduce
